### ISSUE TITLE
Exclude and Include lists sometimes fail to work

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/plugin-TrackingSpamPrevention#98] opened 2023-04-20 00:53 UTC
When an inclusion list is used, for example only allow European countries, the United States, Russia and other countries are not excluded.

The opposite is sometimes true using an exclude list - visitors from the excluded countries still appear in the tracking data.

These examples are from Cloud instances which use the Maxmind City database. According to Maxmind, country accuracy should be 99.8%. It is important to note that both observed cases are using partial IP anonymisation.

**Comment by mattab** [comment] 2023-04-26 03:14
Thanks for reporting this issue. 
Unfortunately we're unable to reproduce the problem. 
**If anyone is reading this and has seen this behaviour, please leave a comment and a screenshot (and ideally how you managed to reproduce).**
If we don't hear more about this issue, we will close it later. Thanks!

**Closed as not planned by mattab** 2023-04-26 03:14 UTC
